//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wszystky
    {
        public int ID { get; set; }
        public string Nazwa { get; set; }
        public System.DateTime Data_wydania { get; set; }
        public decimal Cena { get; set; }
        public string Autor { get; set; }
        public string Wydawnictwo { get; set; }
        public int Rodzaj { get; set; }
    }
}
